### ISSUE TITLE
Deploy dns utils as a Kustomize app

### ISSUE THREAD

**Issue by avnes** [avnes/k8s-at-home#61]
```
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
